// Code generated by hertz generator.

package user

import (
	"github.com/T4t4KAU/webx/mw/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _editMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.MiddlewareFunc(),
	}
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _profileMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		auth.MiddlewareFunc(),
	}
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}
