version: '3.0'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=webx
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "16379:6379"
    volumes:
      - ./script/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./pkg/data/redis/:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always