// Code generated by hertz generator.

package main

import (
	"github.com/T4t4KAU/webx/biz/dal"
	"github.com/T4t4KAU/webx/biz/dal/query"
	"github.com/T4t4KAU/webx/mw/auth"
	"github.com/T4t4KAU/webx/mw/cache"
	"github.com/T4t4KAU/webx/pkg/constant"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/redis/go-redis/v9"
)

func main() {
	initDB()
	initAuth()
	initCache()

	h := server.Default()

	recovery.Recovery()

	register(h)
	h.Spin()
}

func initDB() {
	dal.DB = dal.ConnectDB(constant.MySQLDSN).Debug()
	query.SetDefault(dal.DB)
}

func initAuth() {
	auth.Init()
}

func initCache() {
	cache.RD = redis.NewClient(&redis.Options{
		Addr:     constant.RedisAddr,
		Password: constant.RedisPassword,
		DB:       0,
	})
}
