// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTbUser = "tb_user"

// TbUser mapped from table <tb_user>
type TbUser struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username  string `gorm:"column:username" json:"username"`
	Password  string `gorm:"column:password" json:"password"`
	Email     string `gorm:"column:email" json:"email"`
	Signature string `gorm:"column:signature" json:"signature"`
}

// TableName TbUser's table name
func (*TbUser) TableName() string {
	return TableNameTbUser
}
