// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/T4t4KAU/webx/biz/model/user"
	service "github.com/T4t4KAU/webx/biz/service/user"
	"github.com/T4t4KAU/webx/pkg/mw/auth"
	"github.com/T4t4KAU/webx/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"net/http"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserRegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	err = service.NewUserService(ctx, c).Register(&req)
	if err != nil {
		r := utils.BuildBaseResp(err)
		c.JSON(http.StatusOK, r)
		return
	}

	auth.UserLogin(ctx, c)
}

// Login .
// @router /user/login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	auth.UserLogin(ctx, c)
}

// Profile .
// @router /user/profile [POST]
func Profile(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserProfileReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UserProfileResp)
	u, err := service.NewUserService(ctx, c).Profile(&req)

	r := utils.BuildBaseResp(err)
	resp.User = &u
	resp.StatusCode = r.StatusCode
	resp.StatusMsg = r.StatusMsg

	c.JSON(consts.StatusOK, resp)
}

// Edit .
// @router /user/edit [POST]
func Edit(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserEditReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UserEditResp)

	err = service.NewUserService(ctx, c).Edit(&req)
	r := utils.BuildBaseResp(err)
	resp.StatusCode = r.StatusCode
	resp.StatusMsg = r.StatusMsg

	c.JSON(consts.StatusOK, resp)
}
