// Code generated by hertz generator.

package article

import (
	"github.com/T4t4KAU/webx/pkg/mw/auth"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		auth.MiddlewareFunc(),
	}
}

func _articleMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _editMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _publishMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _hideMw() []app.HandlerFunc {
	// your code...
	return nil
}
