// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameArticle = "article"

// Article mapped from table <article>
type Article struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title     string `gorm:"column:title" json:"title"`
	Content   []byte `gorm:"column:content" json:"content"`
	AuthorID  int64  `gorm:"column:author_id" json:"author_id"`
	Ctime     int64  `gorm:"column:ctime" json:"ctime"`
	Utime     int64  `gorm:"column:utime" json:"utime"`
	Published bool   `gorm:"column:published;not null" json:"published"`
}

// TableName Article's table name
func (*Article) TableName() string {
	return TableNameArticle
}
