// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	article "github.com/T4t4KAU/webx/biz/router/article"
	user "github.com/T4t4KAU/webx/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	article.Register(r)

	user.Register(r)
}
